/*
 *                             Vortex Cafe
 *
 *    This software and documentation are Copyright 2010 to 2015 PrismTech
 *    Limited and its licensees. All rights reserved. See file:
 *
 *                           docs/LICENSE.html
 *
 *    for full copyright notice and license terms.
 */
module SensorData
{
   struct Msg
   {
      string userID;    // User ID
      double temperature; // (in degrees C)
      double power;    // (in Watts)
      double vibrations;    // (in Hertz)
      string time; // current time
   };
   #pragma keylist Msg userID
};
